-- MySQL Script generated by MySQL Workbench
-- Mon May 15 19:43:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TBDFC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TBDFC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TBDFC` DEFAULT CHARACTER SET UTF8MB4 ;
USE `TBDFC` ;

-- -----------------------------------------------------
-- Table `TBDFC`.`Clube`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Clube` (
  `CNPJ` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Fornecedor` (
  `CNPJ` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Cliente` (
  `ClienteID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Data de Nascimento` VARCHAR(45) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Cidade` VARCHAR(45) NOT NULL,
  `Nº` INT NOT NULL,
  PRIMARY KEY (`ClienteID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Pedido` (
  `Número` INT NOT NULL,
  `Data` DATETIME NOT NULL,
  `Nota Fiscal` VARCHAR(45) NOT NULL,
  `Cliente_ClienteID` INT NOT NULL,
  PRIMARY KEY (`Número`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_ClienteID` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_ClienteID`)
    REFERENCES `TBDFC`.`Cliente` (`ClienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Produto` (
  `Código` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cor` VARCHAR(45) NULL,
  `Tamanho` VARCHAR(45) NULL,
  `Valor` DECIMAL(50) NOT NULL,
  PRIMARY KEY (`Código`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Clube/Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Clube/Fornecedor` (
  `Fornecedor_CNPJ` INT NOT NULL,
  `Clube_CNPJ` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_CNPJ`, `Clube_CNPJ`),
  INDEX `fk_Fornecedor_has_Clube_Clube1_idx` (`Clube_CNPJ` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Clube_Fornecedor1_idx` (`Fornecedor_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Clube_Fornecedor1`
    FOREIGN KEY (`Fornecedor_CNPJ`)
    REFERENCES `TBDFC`.`Fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Clube_Clube1`
    FOREIGN KEY (`Clube_CNPJ`)
    REFERENCES `TBDFC`.`Clube` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Cliente/Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Cliente/Fornecedor` (
  `Fornecedor_CNPJ` INT NOT NULL,
  `Cliente_ClienteID` INT NOT NULL,
  PRIMARY KEY (`Fornecedor_CNPJ`, `Cliente_ClienteID`),
  INDEX `fk_Fornecedor_has_Cliente_Cliente1_idx` (`Cliente_ClienteID` ASC) VISIBLE,
  INDEX `fk_Fornecedor_has_Cliente_Fornecedor1_idx` (`Fornecedor_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_Fornecedor_has_Cliente_Fornecedor1`
    FOREIGN KEY (`Fornecedor_CNPJ`)
    REFERENCES `TBDFC`.`Fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ClienteID`)
    REFERENCES `TBDFC`.`Cliente` (`ClienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Item` (
  `Produto_Código` INT NOT NULL,
  `Pedido_Número` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Produto_Código`, `Pedido_Número`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_Número` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_Código`)
    REFERENCES `TBDFC`.`Produto` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_Número`)
    REFERENCES `TBDFC`.`Pedido` (`Número`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Fornecedor/Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Fornecedor/Produto` (
  `Produto_Código` INT NOT NULL,
  `Fornecedor_CNPJ` INT NOT NULL,
  PRIMARY KEY (`Produto_Código`, `Fornecedor_CNPJ`),
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_CNPJ` ASC) VISIBLE,
  INDEX `fk_Produto_has_Fornecedor_Produto1_idx` (`Produto_Código` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_Código`)
    REFERENCES `TBDFC`.`Produto` (`Código`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_CNPJ`)
    REFERENCES `TBDFC`.`Fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Hobby` (
  `HobbyID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`HobbyID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TBDFC`.`Cliente/Hobby`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TBDFC`.`Cliente/Hobby` (
  `Hobby_HobbyID` INT NOT NULL,
  `Cliente_ClienteID` INT NOT NULL,
  PRIMARY KEY (`Hobby_HobbyID`, `Cliente_ClienteID`),
  INDEX `fk_Hobby_has_Cliente_Cliente1_idx` (`Cliente_ClienteID` ASC) VISIBLE,
  INDEX `fk_Hobby_has_Cliente_Hobby1_idx` (`Hobby_HobbyID` ASC) VISIBLE,
  CONSTRAINT `fk_Hobby_has_Cliente_Hobby1`
    FOREIGN KEY (`Hobby_HobbyID`)
    REFERENCES `TBDFC`.`Hobby` (`HobbyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hobby_has_Cliente_Cliente1`
    FOREIGN KEY (`Cliente_ClienteID`)
    REFERENCES `TBDFC`.`Cliente` (`ClienteID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
